remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: How to quantify the actors success ? 
description: Project realised by A.Touré, N.Avetikovi, Q.Zoppis, P.Nguyen, M.Olszewski
show_downloads: True
navigation:
  - title: Data Story
    url: /mainpage
  - title: Example
    url: example
  - title: Longevity
    url: longevity
